# Write your MySQL query statement below
SELECT CUSTOMER_ID,COUNT(CUSTOMER_ID) count_no_trans  from Visits V
LEFT JOIN TRANSACTIONS T ON V.VISIT_ID = T.VISIT_ID 
WHERE TRANSACTION_ID IS NULL
GROUP BY CUSTOMER_ID;